const tourScenes = [
  {
    id: "intro",
    number: "01",
    eyebrow: "Player profile",
    title: "Steven Jia",
    summary: "Software Engineer and Full Stack Developer building web and data applications across Laravel, Vue, React, TypeScript, .NET, and PostgreSQL.",
    facts: [
      "Full Stack Developer Intern at Ocular",
      "BSc Computer Science, Minor in AI · VUW · 2023–2025",
    ],
    label: "IDENTITY DOCK",
    color: "#a855f7",
    position: [-8, 0, 0],
    camera: [-8, 3.7, 6.8],
  },
  {
    id: "experience",
    number: "02",
    eyebrow: "Experience log",
    title: "Building, teaching, and solving",
    summary: "Professional experience spanning multi-tenant product development, technical teaching, device diagnostics, and customer-focused problem solving.",
    facts: [
      "Vue 3, TypeScript, Laravel, REST APIs, and PostgreSQL at Ocular",
      "Python, coding, robotics, and RoboCup tutoring at Scots College",
      "Hardware, software, OS, data-transfer, and customer support at UR Tech",
    ],
    label: "MEMORY VAULT",
    color: "#d946ef",
    position: [0, 0, -9],
    camera: [-2.35, 2.9, -2.7],
  },
  {
    id: "projects",
    number: "03",
    eyebrow: "Build archive",
    title: "Products backed by engineering depth",
    summary: "Six selected CV projects spanning multi-tenant workflows, AI-assisted job tracking, fitness, live data collection, machine learning, and OData integration.",
    facts: [
      "Dependency Map and Power BI OData Demo — tenant-isolated Laravel systems",
      "JobTrack and Kiwi Supplement Watch — AI workflows and live data automation",
      "FitQuest and ML classifiers — tested .NET and Python applications",
    ],
    label: "BUILD DISTRICT",
    color: "#8b5cf6",
    position: [9, 0, 0],
    camera: [9, 4.2, 7.2],
  },
  {
    id: "skills",
    number: "04",
    eyebrow: "Technical loadout",
    title: "A stack that crosses product and systems",
    summary: "A production-focused toolkit covering interfaces, backend services, relational data, integrations, automated testing, CI/CD, and cloud delivery.",
    facts: [
      "Python, PHP, TypeScript, JavaScript, C#, Java, SQL, HTML5, and CSS3",
      "Laravel, Vue 3, React, Next.js, ASP.NET Core, Node.js, and REST APIs",
      "AWS Certified with Docker, GitHub Actions, Vercel, Render, and Supabase",
    ],
    label: "STACK FORGE",
    color: "#6366f1",
    position: [2.5, 0, 9],
    camera: [-1.5, 3.8, 14.8],
  },
  {
    id: "hobbies",
    number: "05",
    eyebrow: "Off-duty archive",
    title: "How I reset and stay curious",
    summary: "Strategy, outdoor challenges, patient observation, and technical experiments keep me balanced and curious outside work.",
    facts: [
      "Strategic board games and collaborative problem solving",
      "Skiing, hunting, and time in challenging outdoor environments",
      "Exploring new frameworks, AI tools, and development ideas",
    ],
    label: "LEISURE VAULT",
    color: "#38bdf8",
    position: [-5.5, 0, 8],
    camera: [-5.5, 3.5, 14.4],
  },
  {
    id: "contact",
    number: "06",
    eyebrow: "Final checkpoint",
    title: "Let’s build something useful",
    summary: "I am ready to discuss software, web, data, and technical support opportunities, project decisions, and implementation trade-offs.",
    facts: [
      "021 119 9859 · steven5115115@gmail.com",
      "github.com/ZiruiJia11 · linkedin.com/in/steven-jia-b78314231",
      "Portfolio: zirui-jia.dev",
    ],
    label: "SIGNAL GATE",
    color: "#c084fc",
    position: [-10, 0, 3],
    camera: [-10, 3.8, 9.5],
  },
];

export default tourScenes;
